import assert from 'node:assert/strict';
import test from 'node:test';
import { classifyOrigin, parseMexInventory } from '../src/main/origin.js';

test('MEX and RTD classification always carries explicit evidence', () => {
  const mex = parseMexInventory([{ path: 'board.mex', source: '<instance name="Spi_Ip"><setting name="Name" value="SpiExternalDevice_0"/></instance>' }]);
  const generated = classifyOrigin('generate/src/Spi_Ip_PBcfg.c', '/* Auto-generated by S32 Configuration Tools. Do not edit. */\nint x;', mex);
  assert.equal(generated.kind, 'mex');
  assert.equal(generated.confidence, 'confirmed');
  assert.match(generated.rule, /생성/);
  assert.ok(generated.anchors.length > 0);

  const rtd = classifyOrigin('RTD/src/Spi_Ip.c', '/* Copyright NXP Semiconductors */\nvoid Spi_Ip_Init(void) {}', mex);
  assert.equal(rtd.kind, 'rtd');
  assert.equal(rtd.confidence, 'confirmed');

  const user = classifyOrigin('src/app.c', 'void App_Run(void) {}', mex);
  assert.equal(user.kind, 'unknown');
  assert.match(user.rule, /근거/);

  const inheritedCopyright = classifyOrigin('src/main.c', '/* Copyright NXP Semiconductors */\nvoid User_Main(void) {}', mex);
  assert.equal(inheritedCopyright.kind, 'unknown');
  assert.equal(inheritedCopyright.label, '사용자 관리 코드');
});
